# Logistic Regression in Python with scikit-learn

Logistic regression is one of the most simple and commonly used machine learning algorithm for two-class classification. It is a statical method to predict binary classes.

Logistic regression is fast and relatively uncomplicated , and its convenient for you to interpret the results.

### Import the packages, functions and classes

In [ ]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
upload=files.upload()

Saving Credit Risk (1).csv to Credit Risk (1).csv


In [ ]:
credit=pd.read_csv('Credit Risk (1).csv')
credit.head()

Age  ActiveLoans  Due90Days  RealEstateLoans  CrLineUtilization  Default
0   45           13          0                6          -0.266443        1
1   40            4          0                0          -0.043743        0
2   38            2          1                0          -0.418246        0
3   30            5          0                0          -1.453289        0
4   49            7          0                1          -0.097392        0

### #Create x and y

In [ ]:
x=credit.drop(['Default'],axis=1)
y=credit['Default']

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(x, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
model=LogisticRegression().fit(x, y)

In [ ]:
model.classes_

array([0, 1])

In [ ]:
model.intercept_

array([-1.00495698])

In [ ]:
model.coef_

array([[-0.01973214,  0.01492053,  0.02732071,  0.02618143,  0.62684781]])

In [ ]:
model.score(x, y)

0.9319533333333333

In [ ]:
model.predict_proba(x)

array([[0.84668922, 0.15331078],
       [0.85345754, 0.14654246],
       [0.87651058, 0.12348942],
       ...,
       [0.93899053, 0.06100947],
       [0.94113131, 0.05886869],
       [0.90004639, 0.09995361]])

In [ ]:
model.predict(x)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
 confusion_matrix(y, model.predict(x))

array([[139631,    343],
       [  9864,    162]])

In [ ]:
 print(classification_report(y, model.predict(x)))

              precision    recall  f1-score   support

           0       0.93      1.00      0.96    139974
           1       0.32      0.02      0.03     10026

    accuracy                           0.93    150000
   macro avg       0.63      0.51      0.50    150000
weighted avg       0.89      0.93      0.90    150000

